capacitorsInfo: capacitorsInfo.o capacitor.o
	gcc -o capacitorsInfo capacitorsInfo.o capacitor.o
	
capacitorsInfo.o: capacitorsInfo.c capacitor.h
	gcc -c capacitorsInfo.c
	
capacitor.o: capacitor.c capacitor.h
	gcc -c capacitor.c